### ISSUE TITLE
✨ feat: 개발서버 사용자 및 transcribe 버킷 추가

### ISSUE THREAD

**Issue by suugit** [Parrotalk/Parrotalk_CD#10]
# Title

- transcribe 테스트를 위한 개발서버 사용자 및 버킷 추가

# TODO

- [ ] 개발 서버 사용자 그룹, 사용자 추가
- [ ] s3, transcribe 권한 추가
- [ ] data 저장 s3 버킷 생성

# etc
