### ISSUE TITLE
✨ feat: kubespray 기반 클러스터 구성

### ISSUE THREAD

**Issue by suugit** [Parrotalk/Parrotalk_CD#14]
# Title

- kubespray 기반 클러스터 구성

# TODO

- [ ] 테라폼-보안그룹 재설정
- [ ] 테라폼-쿠버네티스 연동을 위한 태그 및 역할설정
- [ ] ansible-> kubespray 기반 코드로 변경

# etc

- 기존  ansible 폴더 대신 k8s-cluster-config에 새 폴더 생성
