### ISSUE TITLE
💚 ci/cd: Argo CD 설치

### ISSUE THREAD

**Issue by suugit** [Parrotalk/Parrotalk_CD#7]
# Title

-  Argo CD 설치 및 구성

# TODO

- [ ] ansible 코드로 ArgoCD 설치코드 작성
- [ ] ArgoCD namespace 생성
- [ ] ArgoCD 포트포워딩 설정

# etc

- 흐읍
