### ISSUE TITLE
💚 ci/cd: Argo CD 애플리케이션 배포 테스트

### ISSUE THREAD

**Issue by suugit** [Parrotalk/Parrotalk_CD#8]
# Title

- 개발 쿠버네티스 서버에 Argo CD를 사용한 애플리케이션 배포 테스트

# TODO

- [ ] 테스트용 리액트, 스프링부트 ecr 이미지 준비
- [ ] mainfest 파일 작성 및 Git 저장소에 푸시
- [ ] ArgoCD에서 새 애플리케이션 생성
- [ ] Git 저장소와 연동하여 배포 확인
- [ ] manifest 파일 수정 후 동기화 테스트

# etc

- 흐읍
